# Generated by Django 4.2.4 on 2023-09-20 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitembookitem',
            name='book_item_id',
        ),
        migrations.RemoveField(
            model_name='orderitembookitem',
            name='order_item_id',
        ),
        migrations.DeleteModel(
            name='BookItem',
        ),
        migrations.DeleteModel(
            name='OrderItemBookItem',
        ),
    ]
