# Generated by Django 4.2.4 on 2023-09-06 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_alter_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shop_order_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
