# Generated by Django 4.2.4 on 2023-09-02 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='id_in_warehouse',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='genre',
            field=models.ManyToManyField(to='shop.genre', verbose_name='genre'),
        ),
    ]
