# Generated by Django 4.2.4 on 2023-09-07 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_id_in_warehouse_alter_product_genre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-created',), 'verbose_name': 'Book', 'verbose_name_plural': 'Books'},
        ),
    ]
